In [1]:
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
%config InlineBackend.figure_format='retina'


import numpy as np

In [2]:
x1=np.array([1,2,3])
x2=2*x1

y=np.array([4,6,8])

In [3]:
all_ones=np.ones(x1.shape[0])
X=np.array([all_ones,x1,x2]).T

In [4]:
X.shape

(3, 3)

In [5]:
X

array([[1., 1., 2.],
       [1., 2., 4.],
       [1., 3., 6.]])

In [6]:
def solve_normal_equation(X,y):
    try:
        theta=np.linalg.inv(X.T @ X) @X.T @ y
        return theta
    except np.linalg.LinAlgError:
        print('The matrix is singular')
        print("X.T @ X = \n", X.T @ X)
        return None

In [9]:
matrix1=solve_normal_equation(X,y)
matrix1

The matrix is singular
X.T @ X = 
 [[ 3.  6. 12.]
 [ 6. 14. 28.]
 [12. 28. 56.]]


In [10]:
def solve_normal_equation(X, y):
    try:
        # Solve the linear equation X.T @ X * theta = X.T @ y for theta
        theta = np.linalg.solve(X.T @ X, X.T @ y)
        return theta
    except np.linalg.LinAlgError:
        print('The matrix is singular')
        print("X.T @ X = \n", X.T @ X)
        return None


In [11]:
matrix2=solve_normal_equation(X,y)
matrix2

The matrix is singular
X.T @ X = 
 [[ 3.  6. 12.]
 [ 6. 14. 28.]
 [12. 28. 56.]]



Finding the inverse of a matrix can make small mistakes bigger, which might give us wrong answers. But if we solve equations directly, we can avoid this issue. Also, finding the inverse of a big matrix can take a lot of time and computer power. But solving equations directly is quicker and needs less power.
That's why using np.linalg.solve instead of directly computing the matrix inverse is better in terms of numerical stability, efficiency, and robustness.